name: "Create release asset"

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run npm install
        run: |
          npm install

      - name: Create Artifact
        run: |
          npm run build
          npm run plugin-zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ms-featured-image
          path: ms-featured-image.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ms-featured-image.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
